/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: mtmanapi.i

#ifndef SWIG_mtmanapi_WRAP_H_
#define SWIG_mtmanapi_WRAP_H_

class Swig_memory;

class SwigDirector_PumpReceiver : public PumpReceiver
{
 public:
  SwigDirector_PumpReceiver(int swig_p);
  virtual ~SwigDirector_PumpReceiver();
  virtual void OnPump(int code, int typ, void *data, void *param);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
